[package]
name = "fdtrace-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { workspace = true, optional = true }
log = { workspace = true }

[lib]
path = "src/lib.rs"
