[package]
name = "fdtrace"
version = "0.1.0"
edition = "2021"


[dependencies]
structopt = "0.3.26"
json = "0.12.4"
tempfile = "3.14.0"
anyhow = "1.0.93"
log = "0.4.22"
env_logger = "0.11.5"
itertools = "0.13.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
